vich_uploader:
    db_driver: orm

    mappings:
        galerie_images:
            uri_prefix: '%env(resolve:GALERIE_IMAGES_PATH)%'
            upload_destination: '%kernel.project_dir%/public%env(resolve:GALERIE_IMAGES_PATH)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false