vich_uploader:
    db_driver: orm

    mappings:
       galerie_images:
           uri_prefix: '%galerie_images%'
           upload_destination: '%kernel.project_dir%/public%galerie_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
